version: 0.2

env:
  secrets-manager:
    SONAR_LOGIN: sonar:LOGIN
    SONAR_HOST: sonar:HOST
    SONAR_ORGANIZATION: sonar:ORGANIZATION
  variables:
    SOURCE_SRC: "src"
    SONAR_PROJECTKEY: "Cloud2gether_Cloud2Gether.Documentation"
    HUGO_VERSION: "0.155.0"
    GO_VERSION: "1.21.6"
phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - echo "=== Installing Hugo Extended ==="
      - wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
      - dpkg -i hugo_extended_${HUGO_VERSION}_linux-amd64.deb
      - hugo version

      - echo "=== Installing Go (required for Hugo modules) ==="
      - wget -q https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
      - tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
      - export PATH=$PATH:/usr/local/go/bin && go version

      - echo "=== Installing PostCSS dependencies ==="
      - cd $CODEBUILD_SRC_DIR/$SOURCE_SRC && npm install

      - echo "=== Fetching Hugo modules (Docsy) ==="
      - cd $CODEBUILD_SRC_DIR/$SOURCE_SRC && export PATH=$PATH:/usr/local/go/bin && hugo mod get
  pre_build:
    commands:
      # - echo "Executing pre-build phase"
      # - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      # - unzip ./sonar-scanner-cli-5.0.1.3006-linux.zip
      # - export PATH=$PATH:./sonar-scanner-5.0.1.3006-linux/bin/
      - export PULLREQUEST_NUMBER=$(echo $CODEBUILD_WEBHOOK_TRIGGER | grep "pr/" | cut -d "/" -f2)
  build:
    commands:
      - echo "Executing build phase"
      - cd $CODEBUILD_SRC_DIR/$SOURCE_SRC
      - export PATH=$PATH:/usr/local/go/bin && hugo --gc --minify -e production
      - echo $PULLREQUEST_NUMBER
      - if [ -z "$PULLREQUEST_NUMBER" ] ;
        then
          sonar-scanner -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST -Dsonar.projectKey=$SONAR_PROJECTKEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.sources=$CODEBUILD_SRC_DIR/$SOURCE_SRC/public;
        else
          sonar-scanner -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=$SONAR_HOST -Dsonar.projectKey=$SONAR_PROJECTKEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.sources=$CODEBUILD_SRC_DIR/$SOURCE_SRC/public -Dsonar.pullrequest.key=$PULLREQUEST_NUMBER;
        fi
      - sleep 15
      - curl -u $SONAR_LOGIN:"" https://sonarcloud.io/api/qualitygates/project_status?projectKey=$SONAR_PROJECTKEY >result.json
      - cat result.json
artifacts:
  discard-paths: no
  base-directory: src/public
  files:
    - "**/*"
